# Generated by Django 5.1.2 on 2024-10-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
